config/routes.rb
Rails.application.routes.draw do
  root to: 'static_pages#root'

  # resources :users, only: [:new, :create]
  # resource :session

  namespace :api, defaults: {format: :json } do
    resource :session, only: [:create, :destroy]
    resources :users, only: [:show, :create]
    resources :loops, only: [:show, :create, :update, :destroy]
    resources :verses, only: [:show, :create, :update, :destroy]
    resources :measures, only: [:show] if Rails.env.development?
    resources :measures, only: [:update]
    resources :measure_loops, only: [:show] if Rails.env.development?
    resources :measure_loops, only: [:create, :update, :destroy]
  end
end

app/views/layouts/_header.html.erb
<nav class="navbar navbar-default navbar-fixed-top" role="navigation">
<div class="container container-fluid">
  <div class="navbar-header">
    <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1">
      <span class="sr-only">Toggle navigation</span>
      <span class="icon-bar"></span>
      <span class="icon-bar"></span>
      <span class="icon-bar"></span>
    </button>
    <a class="navbar-brand" href="#">Dianthus</a>
  </div>

  <div class="collapse navbar-collapse pull-right" id="bs-example-navbar-collapse-1">
    <% if signed_in? %>
    <%= button_to "Sign out", session_url, method: :delete, class: "btn btn-primary navbar-btn" %>
    <% else %>
    <ul class="nav navbar-nav">
      <li><%= link_to "Log in", new_session_url %></li>
      <li><%= link_to "Sign up", new_user_url %></li>
    </ul>
    <% end %>
  </div>
</div>
</nav>

<% if flash[:errors] %>
<div class="alert alert-warning alert-dismissible" role="alert">
   <button type="button" class="close" data-dismiss="alert"><span aria-hidden="true">&times;</span><span class="sr-only">Close</span></button>
<%= flash[:errors].join("<br>") %>
</div>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Fermata</title>
  <%= stylesheet_link_tag    "application", media: "all" %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>
  <meta name="viewport"
        content="width=device-width,
                 initial-scale=1,
                 user-scalable=no">
</head>
<body>
  <%# render partial: "layouts/header" %> <!-- TODO: figure out a less
                                               obtrusive session
                                               management UX -->
  <!-- <div class="container-fluid"> -->
    <%= yield %>
  <!-- </div> -->
</body>
</html>